spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webdb
    username: webuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    org.ruu.bootthymeleafjpa: info
    org.ruu: debug